columns:
  edad:
    type: integer
    range: [18, 99]
  email:
    type: string
    pattern: '^[\w\.-]+@[\w\.-]+\.\w{2,}$'
  fecha_registro:
    type: date
    format: '%Y-%m-%d'
  precio:
    type: number
    min: 0.0
  nombre:
    type: string
    min_length: 1
    max_length: 255
